version: '2'
services:
  nexus:
    image: sonatype/nexus3
    volumes:
      - /nexus-data:/nexus-data
    restart: always
  nginx:
    build:
      context: .
      dockerfile: ./nginx-dockerfile
    ports:
      - "443:443"
    links:
      - nexus:8081
    restart: always
    depends_on:
      - nexus